---
title: BYBORRE
url: http://byborre.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
    permalink: "/products/:path/"
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  uploads:
    title: Uploads
    output: true
email: mail@byborre.com
description: |
  BYBORRE makes textile with embedded technology. Enabling a new way of digital interaction.
baseurl: ''
twitter_username: byB0RRE
github_username: byborre
facebook_username: byborre
instagram_username: byborre
markdown: kramdown
highlighter: rouge
exclude:
- node_modules
- gulpfile.js
- package.json
permalink: pretty
