# Site settings
title: BYBORRE
email: mail@byborre.com
description: > # this means to ignore newlines until "baseurl:"
  BYBORRE makes textile with embedded technology. Enabling a new way of digital interaction.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://byborre.com" # the base hostname & protocol for your site
twitter_username: byB0RRE
github_username:  byborre
facebook_username: byborre
instagram_username: byborre
markdown: redcarpet
highlighter: pygments
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: pretty
collections:
  products:
    output: true
    permalink: /products/:path/
  projects:
    output: true
    permalink: /projects/:path/
